sudo: false

language: java
jdk:      oraclejdk8

before_install:
  # use gradle daemon since we're calling it more than once
  - echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties

install:  ./gradlew clean assemble
script:   ./gradlew check

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

