sudo: false
language: java
jdk: oraclejdk8
before_install:
- echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./gradlew -PalvchUsername=$ARTIFACTORY_USERNAME
  -PalvchPassword=$ARTIFACTORY_PASSWORD -Penv=staging clean assemble; fi
- if [ "$TRAVIS_BRANCH" == "prod" ]; then ./gradlew -PalvchUsername=$ARTIFACTORY_USERNAME
  -PalvchPassword=$ARTIFACTORY_PASSWORD -Penv=prod clean assemble; fi
script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then ./gradlew -PalvchUsername=$ARTIFACTORY_USERNAME
  -PalvchPassword=$ARTIFACTORY_PASSWORD -Penv=staging check; fi
- if [ "$TRAVIS_BRANCH" == "prod" ]; then ./gradlew -PalvchUsername=$ARTIFACTORY_USERNAME
  -PalvchPassword=$ARTIFACTORY_PASSWORD -Penv=prod check; fi
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/native/"
  - "$HOME/.gradle/wrapper/"
after_success:
- bash <(curl -s https://codecov.io/bash)
- ls $TRAVIS_BUILD_DIR/build/libs
notifications:
  webhooks:
  - https://buildtimetrend.herokuapp.com/travis
deploy:
  provider: releases
  api_key:
    secure: zf4KDdW5xoDFepfO+x5poBT31MPzVS/iRJHK0eyPLsj5rl82mn/mzCV1QDSt8KqNnAfYU5McAZLGr4B+qTEYDx4GofmJDPacx3ZeP8h6GI8Ow4Svk6nXLZxJkaVGh1E1fNnPk33w2zWiPHZhcnaEgqDeT6ZHZAriYwJz15W83i7h/chmuXCADwvsO/ahR834oWMypdV2Bx1alGlegMeddEGZk5n0PxMvuru6oKMnyg6VMuqEpqEeL6/n2vZ9m0N0xKi0lzIfRgZ5Y83CDC1ltDfTKS9Vmay0hUl5i+gFwn28Y/yp6ZVJPKa7OoyuEL2Y3UhB6gAYt2TfcmFtK7Nf+luJ0K/iZQQ2Jddx178SvmMco4GSPVCHZ78lOCcRKxPzZ5nKroba/Q++7EHo0H66pH800OeGlN6/TiFwMzGIWIhwdgvKCqQrNLohAtEsxFI6sESxqyW1t5kDoPPEDCadTzACBO5OfjeyIT/IeGahNdmdQFL79dnPfT+y8FIEVrsgSfzq2vXxMmZPTz6AKw/6J6LCV/rcQCevblvSAMmgUAdVh0a70+Qo+b4r2SQ83ltW7qhhN6qaB1gFNlSPkRJLQiLV5eOETs92HPzCXZenEOXnzKPGaVlCyE51sbhUFUkqk/HoVWjE0Kp6SG9l75um6b1I9cHH5cDRjwR0idqxAps=
  file: '$TRAVIS_BUILD_DIR/build/libs/$TRAVIS_TAG.jar'
  skip_cleanup: true
  on:
    tags: true
