create table JobOffer (
  id bigint generated by default as identity (start with 1),
  version bigint,
  publicationstartdate date not null,
  publicationenddate date,
  job_title varchar(255) not null,
  job_description varchar(255) not null,
  job_workingtimepercentagefrom integer not null,
  job_workingtimepercentageto integer not null,
  job_startdate date,
  job_enddate date,
  job_location_countrycode varchar(255) not null,
  job_location_locality varchar(255) not null,
  job_location_postalcode varchar(255) not null,
  job_location_additionaldetails varchar(255),
  company_name varchar(255) not null,
  company_countrycode varchar(255) not null,
  company_street varchar(255) not null,
  company_housenumber varchar(255) not null,
  company_locality varchar(255) not null,
  company_postalcode varchar(255) not null,
  company_phonenumber varchar(255) not null,
  company_email varchar(255) not null,
  company_website varchar(255) not null,
  company_postbox_number varchar(255) not null,
  company_postbox_locality varchar(255) not null,
  company_postbox_postalcode varchar(255) not null,
  contact_title varchar(255) not null,
  contact_firstname varchar(255) not null,
  contact_lastname varchar(255) not null,
  contact_phonenumber varchar(255) not null,
  contact_email varchar(255) not null,
  application_telephonic boolean not null,
  application_written boolean not null,
  application_electronic boolean not null,
  primary key (id)
);

create table JobOffer_job_languageskills (
  JobOffer_id bigint not null,
  language varchar(255) not null,
  spokenlevel varchar(255) not null,
  writtenlevel varchar(255) not null
);

alter table JobOffer_job_languageskills
add constraint FK_JOBOFFER_01
foreign key (JobOffer_id) references JobOffer;
